version: "3"
services:
  cassandra1:
    image: cassandra:latest
    ports:
      - "9042:9042"
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=TEST_CLUSTER
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    restart: "always"
  cassandra2:
    image: cassandra:latest
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TEST_CLUSTER
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    container_name: cassandra2
    restart: "always"
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TEST_CLUSTER
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    restart: "always"

  # cassandra3:
  #   image: cassandra:latest
  #   container_name: cassandra3
  #   ports:
  #     - "9044:9042"
  #     - "9162:9160"
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=Clusterino
  #     - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
  #     - CASSANDRA_AUTO_BOOTSTRAP=true
  #   mem_limit: 4g
  #   volumes:
  #     - /Users/sbart/OneDrive - put.poznan.pl/Semestr VI/BigData/CassandraProject/cassandra/3:/var/lib/cassandra
  #   restart: always
