version: "3"
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TEST_CLUSTER
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    restart: "always"

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TEST_CLUSTER
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    restart: "always"

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TEST_CLUSTER
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    restart: "always"
